name: Actions

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install tox
      run: python3.7 -m pip install tox
    - name: Run tests
      run: python3.7 -m tox
  build1:
    name: Build manylinux1
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Build cp37
      id: build-cp37
      uses: ./.github/actions/build-manylinux1
      with:
        python-version: cp37
    - name: Upload wheel
      uses: actions/upload-artifact@master
      with:
        name: whl-manylinux1-cp37
        path: ${{ steps.build-cp37.outputs.wheel-path }}
    - name: Upload sdist
      uses: actions/upload-artifact@master
      with:
        name: sdist
        path: ${{ steps.build-cp37.outputs.sdist-path }}
